services:
  database: 
    image: mongo
    environment: 
      MONGO_DB: ${DB_NAME}
      MONGO_USER: ${DB_USER}
      MONGO_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes: 
      - "mongo-data:/data/db"

  api: 
    build: .
    volumes: 
      - ".:/app"
    depends_on: 
      - database
    ports:
      - "8000:8000"
    environment: 
      MONGO_DB: ${DB_NAME}
      MONGO_USER: ${DB_USER}
      MONGO_PASSWORD: ${DB_PASSWORD}
      DB_HOST: expenses
      DB_PORT: ${DB_PORT}

volumes: 
  mongo-data:
    